config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'

  get 'books' => 'homes#index', as: 'main_page'

  post 'books' => 'homes#create'
  get 'books/:id' => 'homes#show', as: 'book'
  patch 'books/:id' => 'homes#update', as: 'update_book'
  get 'books/:id/edit' => 'homes#edit', as: 'edit_book'
  delete 'books/:id' => 'homes#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: "successfully"
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id,), notice: "successfully"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "successfully"
  end




private
  def book_params
    params.require(:book).permit(:title,:body) #require(テーブル名)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/edit.html.erb
<div class = "margin">

    <h1>EditingBook</h1>

    <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
        <% if @book.errors.any? %>
            <div id="error_explanation">
                <ul class = "error_list">
                    <h4 class = "error_title"><%= pluralize(@book.errors.count, "error") %> prohibited this map from being saved:</h2>

                    <% @book.errors.full_messages.each do |message| %>
                        <li class="error_msg"><%= message %></li>
                    <% end %>

                </ul>
            </div>
        <% end %>

        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Body</h4>
        <%= f.text_area :body %>
        <div class = "update_button">
            <%= f.submit "Update Book" %>
        </div>
        <div class = "show_links">
            <%= link_to "show", book_path(@book.id) %>
            <p>|</p>
            <%= link_to "back", main_page_path %>
        </div>
    <% end %>

</div>

app/views/homes/index.html.erb
<p class = "notice"><%= notice %></p>

<div class = "margin">

    <h1>Books</h1>
    <table class = "index_main">
    <tr class = "index_main">
        <th class = "index_title">Title</th>
        <th class = "index_body">Body</th>
        <th colspan="3"></th>
    </tr>

        <% @books.each do |book| %>
            <tr>
                <td class = "book_title"><%= book.title %></td>
                <td class = "book_body"><%= book.body %></td>
                <td class = "links"><%= link_to "show", book_path(book) %>
                <%= link_to "edit", edit_book_path(book.id) %>
                <%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
            </tr>
        <% end %>
    </table>




    <div>
        <h1>NewBook</h1>
        <%= form_with model:@book, url:'/books',local:true do |f| %>
                <% if @book.errors.any? %>
                    <div id="error_explanation">
                        <ul class = "error_list">
                            <h4 class = "error_title"><%= pluralize(@book.errors.count, "error") %> prohibited this map from being saved:</h2>

                            <% @book.errors.full_messages.each do |message| %>
                                <li class="error_msg"><%= message %></li>
                            <% end %>

                        </ul>
                    </div>
                <% end %>


        <h4>Title</h4>
        <%= f.text_field :title %>
            <h4>Body</h4>
            <%= f.text_area :body %>
            <div>
                <%= f.submit 'Create Book' %>
            </div>
        <% end %>
    </div>


</div>

app/views/homes/show.html.erb
<p class = "notice"><%= notice %></p>

<div class = "margin">

    <div class = "show">
        <h4 class = "show_title">Title:</h4><%= @book.title %>
    </div>

    <div class = "show">
        <h4 class = "show_body">Body:</h4><%= @book.body %>
    </div>
    <div class = "show_links">
        <%= link_to "Edit", edit_book_path(@book.id) %>
        <p>|</p>
        <%= link_to "Back", main_page_path %>
    </div>
</div>

app/views/homes/top.html.erb
<div class = "margin">
  <h1>ようこそBookersへ</h1>
    <p class = "honbun">ここは本の感想をレビューするサイトです</p>
    <p class = "honbun">みんなで書き込もう</p>
  <span class = "honbun">
    <%= link_to "start", main_page_path %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




    <%= yield %>
  </body>
</html>